#!/usr/bin/env bash
set -eu

top_builddir="${abs_top_builddir:-$(pwd)}"
cd "$top_builddir"

tests/gen_screen_mode_dumps.sh

mkdir -p docs/assets/screens/png
cp .tmp/screen-dumps/png/screen_*_mode_*.png docs/assets/screens/png/

python3 - <<'PY'
from pathlib import Path
import re

repo = Path('.')
g15stats_c = repo / 'g15stats.c'
screens_md = repo / 'docs' / 'screens.md'
png_dir = repo / 'docs' / 'assets' / 'screens' / 'png'

text = g15stats_c.read_text(encoding='utf-8', errors='replace')

pattern = re.compile(r'case\s+(SCREEN_[A-Z0-9_]+):\s+return\s+"([^"]+)";')
screen_order = []
for const, label in pattern.findall(text):
    if const == 'SCREEN_UNKNOWN':
        continue
    if const not in [c for c, _ in screen_order]:
        screen_order.append((const, label))

header = """# Screens

This page is generated by `tests/update_screens_docs.sh`.

- `Mode 0` and `Mode 1` are triggered by `L4`.
- Images are rendered from real frame dumps and upscaled `3x` (480x129 minimum) for readability.
- Some screens do not change with mode, so `Mode 0` and `Mode 1` may look identical.

## Navigation Buttons

| Button | Action |
|--------|--------|
| **L2** | Previous screen |
| **L3** | Next screen |
| **L4** | Toggle mode for current screen |
| **L5** | Toggle submode / info rotation |
"""

lines = [header.rstrip(), ""]

screen_index = 0
for const, label in screen_order:
    if const == 'SCREEN_SUMMARY' or const.startswith('SCREEN_'):
        mode0 = png_dir / f'screen_{screen_index}_mode_0.png'
        mode1 = png_dir / f'screen_{screen_index}_mode_1.png'
        if not mode0.exists() and not mode1.exists():
            screen_index += 1
            continue

        lines.append(f"## Screen {screen_index} - {label}")
        lines.append("")
        if mode0.exists():
            lines.append("Mode 0")
            lines.append("")
            lines.append(f"![{label} mode 0](assets/screens/png/screen_{screen_index}_mode_0.png)")
            lines.append("")
        if mode1.exists():
            lines.append("Mode 1")
            lines.append("")
            lines.append(f"![{label} mode 1](assets/screens/png/screen_{screen_index}_mode_1.png)")
            lines.append("")

        screen_index += 1

screens_md.write_text("\n".join(lines).rstrip() + "\n", encoding='utf-8')
print(f"updated {screens_md}")
PY

echo "Updated docs/screens.md and docs/assets/screens/png"
